# Site
title:              Nithish Raghunandanan
bio:                'An all-round Hacker who loves to build cool products over short spans of time.'
description:        "Working at the intersection of Data, Software & Startups"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://nithishr.com/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-86965633-3
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
# facebook:           username
linkedin:           nithishr1
github-url:         nithishr
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#xing:              username
devpost:            nithishr
medium:            '@nithishr'
twitter:            nithishr
instagram:          nithishr
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
youtube:           getnithishr
# youtube-channel:  NithishR
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
